### ISSUE TITLE
Support Items

### ISSUE THREAD

**Issue by thailandmatt** [byuoitav/team#1010]
- [x] JRCB Creston Switcher "is still not working"
- [x] Just Add Power dying in CONF?
- [x] Nyle's Pi
- [x] Projectors in EB 425
- [x] After display locking up, why no worky on z pattern?
- [x] G series of Sony TVs don't allow menu selection of output to headphone jack AND speakers at the same time - can we force that with the API?

**Comment by jpw547** [comment]
Could not replicate the z-pattern issue. I could still reach the device monitoring page from both the locked and loading screens on both the cherry and blueberry UIs.

**Comment by werndog** [comment]
TV thing should be doable with the setAudioVolume function. Just need a TV to test it on.

**Comment by werndog** [comment]
Tv's cannot do speaker link through the API
