### ISSUE TITLE
Why no worky when they go offline

### ISSUE THREAD

**Issue by dannyrandall** [byuoitav/team#1011]
Get a pi going, then unplug the uplink port from the switch. It stops working :( WHY

**Comment by werndog** [comment]
Tested and it worky...? Gotta ask Anthony for a time when it happened.

**Comment by thailandmatt** [comment]
Test in 1006 and see if it happens

**Comment by thailandmatt** [comment]
Resolved - so we have to :
1) install dnsmasq
2) update the dhcpcd.conf to have 127.0.0.1 as the first nameserver listed
3) add the /etc/docker/daemon.json file to specify the dns
