### ISSUE TITLE
fix couch-db repl

### ISSUE THREAD

**Issue by dannyrandall** [byuoitav/team#1017]
Nothing is currently breaking, we'll return to this when we have issues again

**Comment by xuther** [comment]
When you say “fix” what do you mean?

**Comment by CalebLarsen** [comment]
When it's put onto a pi, it needs to be reset before it'll work

**Comment by xuther** [comment]
Logs?

**Comment by dannyrandall** [comment]
```

**Comment by dannyrandall** [comment]
jk i fixed this forever ago lol
