### ISSUE TITLE
Touchpanel evaluations

### ISSUE THREAD

**Issue by dannyrandall** [byuoitav/team#1038]
- [x] Get a panel
- [x] Get a Compute Module
- [x] Evaluate it
- [x] Create a compare/contrast document for business team to review

Ask @danielwells if there are any questions about them.

**Comment by thailandmatt** [comment]
- [ ] Test viewing angles of ACME panel
- [ ] Test our image on ACME panel
- [ ] Use ACME panel to display Atlona web interface
- [ ] Point normal Pi screen to Atlona web interface
