### ISSUE TITLE
Shure Microphone firmware check

### ISSUE THREAD

**Issue by dannyrandall** [byuoitav/team#1043]
- [ ] Get missing RCVs and MICs so they are monitored
- [ ] Make sure all of the IP addresses are correct
- [ ] Update the firmware on those that need it

**Comment by thailandmatt** [comment]
- [ ] Get missing RCVs and MICs so they are monitored
- [ ] Make sure all of the IP addresses are correct
- [ ] Update the firmware on those that need it
