### ISSUE TITLE
Wowza HTML5

### ISSUE THREAD

**Issue by jessemillar** [byuoitav/team#109]
Investigate what is needed to do media capture and streaming using the Wowza server system for Learning Suite.

**Comment by jessemillar** [comment]
Not looking promising.

Article: https://www.html5rocks.com/en/tutorials/getusermedia/intro/
Support: http://caniuse.com/#feat=stream

**Comment by jessemillar** [comment]
Based on [this one comment](https://www.wowza.com/forums/showthread.php?54494-HTML5-getUserMedia-record-webcam-both-audio-and-video), if we're moving forward with HTML5, we should look into [Wowza's WebRTC](https://www.wowza.com/products/capabilities/webrtc-streaming-software) product (which we have to request access to).

**Comment by danclegg** [comment]
@jessemillar I think we have a streaming engine license, but I'll reach out to wowza to see what they say.

**Comment by jessemillar** [comment]
@danclegg Any news on the license?

**Comment by danclegg** [comment]
Our licensing folk are working with Wowza reps to get the best educational pricing. We also need approval from our business folk for a purchase. Apparently, _another_ group at the university has a streaming license, but not our organization.

**Comment by jessemillar** [comment]
Ah. Keep me posted.
