### ISSUE TITLE
Make a GitLab account for password store access

### ISSUE THREAD

**Issue by jessemillar** [byuoitav/team#113]
Go [here](https://gitlab.com/users/sign_in) to make a GitLab account so you have access to our shared password store through [gopass](https://www.justwatch.com/gopass/). Documentation on how to configure the password store on your machine will follow shortly.

- [x] @danclegg 
- [ ] @danielwells 
- [x] @jessemillar
- [x] @dgrandall 
- [x] @xuther 
- [ ] @djallred 
- [x] @c-Monster

**Comment by danclegg** [comment]
@jessemillar Is this a secure place for a password store?

**Comment by jessemillar** [comment]
It's a private repo and it's encrypted with GPG. Even if someone got the store downloaded, they couldn't get to the passwords without our private keys.

**Comment by jessemillar** [comment]
Documentation [here](https://github.com/byuoitav/team/wiki/Team-Password-Store).
