### ISSUE TITLE
Set up your password store

### ISSUE THREAD

**Issue by jessemillar** [byuoitav/team#114]
Follow the documentation [here](https://github.com/byuoitav/team/wiki/Team-Password-Store) to install and configure your password store so you can have access to the team's shared credentials.

- [x] @danclegg 
- [ ] @danielwells 
- [x] @jessemillar
- [x] @dgrandall 
- [x] @xuther 
- [ ] @djallred 
- [x] @c-Monster

**Comment by c-Monster** [comment]
I followed the instructions in the documentation. We'll see if it actually works. SSH does not work on the AV LAN.

**Comment by danclegg** [comment]
Not entirely trivial to set up, but I got it done

**Comment by jessemillar** [comment]
@danclegg Hey. I gave you the option of paying a couple bucks/month for 1Password/LastPass. You chose your pain.

**Comment by danclegg** [comment]
@jessemillar Well I'm already up and running with LastPass for my own stuff, but maybe I'm just a glutton for punishment when it comes to the team store.
