### ISSUE TITLE
Web/Mobile Working!

### ISSUE THREAD

**Issue by dannyrandall** [byuoitav/team#1140]
I'll add comments as we find tasks that need to be done so that we don't lose track of anything.

**Comment by dannyrandall** [comment]
- [ ] Have go serve the angular stuff
- [ ] Get the docker container for https://github.com/byuoitav/ui built
- [ ] Get it running in AWS
- [ ] Ask to power off on exit
  - Should be a command send from the frontend

@mjsmith3 @jpw547 add your own comments if you think of things that need to be added so we can keep track of where everyone is at.

**Comment by dannyrandall** [comment]
We also need to update the `Client.State` based on incoming events. I think it would make the most sense to create a [messenger](https://github.com/byuoitav/central-event-system/blob/master/messenger/connection.go#L105) for the backend that subscribes to all events (`"*"`). That messenger should distribute events to the appropriate clients, based on the `AffectedRoom` data of the event.

Once a client gets an event, it should update what it has stored for the state of the room and send an updated room down to the frontend.

**Comment by dannyrandall** [comment]
- [ ] The URL showing on the ui should be configurable and retrived along with the code from the backend.

**Comment by dannyrandall** [comment]
- [ ] Send the correct input down to the front end (get it from the ui config). Right now we are always sending HDMI
- [ ] "Loading" indication after clicking enter on login page

**Comment by dannyrandall** [comment]
Regarding the messenger one above, let's change it to create a messenger specific to each client.

- [ ] Create a messenger & subscribe to the appropriate room while registering the client
- [ ] Update the room based on incoming events

**Comment by dannyrandall** [comment]
- [ ] Fix clicking buttons going back to the "select preset" page

**Comment by mjsmith3** [comment]
- [ ] Figure out why new input won't highlight, and why the volume only works some of the time.

**Comment by dannyrandall** [comment]
- [ ] Fix exit room popup not showing up
- [ ] Fix tab highlighting (and go to tab on page refresh)
- [ ] Fix input change on pi not syncing to phone
- [ ] Fix blank not showing as current input

**Comment by dannyrandall** [comment]
- [ ] Help Requests should route to SMEE with the message
