### ISSUE TITLE
Figure out policy storage strategy for OPA

### ISSUE THREAD

**Issue by bwinterton** [byuoitav/team#1155]

**Comment by dannyrandall** [comment]
Out of curiosity....How do we want to store policies?

**Comment by bwinterton** [comment]
We'll store them in this repo https://github.com/byu-oit/av-opa-policies. 

It's in the generic OIT org as it needs to be private and then in the cases where we need secrets interlaced we'll do that at build time. 

The repo will have a pipeline that will build the policies and dump them into an s3 bucket and OPA will be able to periodically reach out and check for updated policies.
