### ISSUE TITLE
Allow for stage and deployment builds based on branch

### ISSUE THREAD

**Issue by jessemillar** [byuoitav/team#117]
[This Circle documentation](https://circleci.com/docs/1.0/configuration/#deployment) will help.

It looks like Circle suggests using the **master** branch as "stage" and a **production** branch as the one that pushes to prod. I believe their reasoning behind this is that you have to be merging into master to mandate a pull request and it's smarter to do pull requests before everything is smashed together and about to go into production.

**Comment by jessemillar** [comment]
The alternative is treating **master** as the production branch and having a **stage** branch for staging. The issue here is that you can't have a formal GitHub pull request when merging a branch, say, **feature/awesome-thing** into the **stage** branch. You can only have pull requests when merging into **master**.

Both the first option and what I've mentioned in this comment would have the same effect of deploying campus-wide or only to a subset of development Pi's, but I believe the **master**=stage and **production**=production option is the superior choice.

**Comment by dgrandall** [comment]
Is it possible to merge **master** into another branch (i.e. **production**?)+

**Comment by jessemillar** [comment]
@dgrandall As we discovered the other day, it IS possible to merge **master** into another branch. If we set up branch protection on the other branch, a merge mandates a pull request which will give a nice, big, green "Merge" button that will trigger the production deployment.
