### ISSUE TITLE
Decide on a merged branch policy

### ISSUE THREAD

**Issue by jessemillar** [byuoitav/team#118]
Do we delete merged branches? Or leave them there for historic/backup reasons?

**Comment by dgrandall** [comment]
Since all of our commits saved on Github, my vote would be to delete branches after they are merged into master.

**Comment by danclegg** [comment]
There are reasons I have kept old branches around, especially if there is
continued development on the same goal/fix for which the branch was made.
There is potential for multiple merges from a branch, though a handful may
be far too many.

I'm for leaving _some_ old branches as needed, but leaning toward deletion
as the rule.
