### ISSUE TITLE
update README on raspi-deployment-microservice

### ISSUE THREAD

**Issue by c-Monster** [byuoitav/team#120]
I banged my head against the wall until Joe told me it was out of date

**Comment by jessemillar** [comment]
Yeah. That's the downside of working too fast to hit a deadline. In situations like that, it's best to read the code instead of the documentation, or at least compare the latest change date on the README with the latest commit on the code. If they don't match, there's probably an issue.

**Comment by jessemillar** [comment]
Fixed here: https://github.com/byuoitav/raspi-deployment-microservice/pull/26
