### ISSUE TITLE
As a user I want to be able to view a schedule of the room

### ISSUE THREAD

**Issue by xuther** [byuoitav/team#129]
- [x] Validate angular data bindings are working
- [x] Make sure python is updating local `.db` regularly
- [x] Update to `stretch`, validate schedule appears correctly

**Comment by dannyrandall** [comment]
For some reason, the scheduling is showing up fine on newer versions of Chrome, but not on the pi's version. I will try updating to stretch and downloading a newer version to check if that resolves the issue.

[ ] Update to `stretch`, validate schedule appears correctly

**Comment by dannyrandall** [comment]
The issue was that I was deleting `openssl` from the container. Adding that back in made it so the requests to the exchange server worked. Closing this issue now.
