### ISSUE TITLE
Rewrite AVAPI and Event Router to use the new structs

### ISSUE THREAD

**Issue by xuther** [byuoitav/team#142]
- [x] Move Event Node into Common Package
- [x] Rewrite AV-API
- [x] Rewrite Event Router
- [x] Rewrite Touchpanel UI
- [x] Rewrite Event Translator
- [x] Rewrite Divider Sensors
- [x] Test and validate each service

**Comment by jpw547** [comment]
I re-wrote divider sensors and AV-Api, but they still need some testing and validation

**Comment by jpw547** [comment]
The panels in 1101 and 1108 are getting the config file from the CouchDB now, and they show that they have the correct information to allow screen sharing, but they don't seem to show that feature on the screen. I can't fully validate that the divider sensors are working correctly until we can get this sharing button back on the screen, so I will look into that as I re-write the touchpanel-ui.

**Comment by xuther** [comment]
I just finished up the Event-Router. It looks like the event-infrastructure and base packages were split between `byuoitav/messenger` and `byuoitav/common`.
