### ISSUE TITLE
Default to Single Select displays rather than multi-selecting

### ISSUE THREAD

**Issue by dannyrandall** [byuoitav/team#144]
- [x] Remove multi-select

**Comment by xuther** [comment]
Clarification: Don't allow select of multiple screens.

**Comment by dannyrandall** [comment]
- [ ] Change to spinner after clicking power on
- [ ] Add management console

**Comment by dannyrandall** [comment]
Adding the final changes in https://github.com/byuoitav/touchpanel-ui-microservice/pull/389. These haven't been verified by the business team yet, but the concepts were discussed and approved.

**Comment by dannyrandall** [comment]
I validated the changes looked correct in 1108. Closing this user story.
