### ISSUE TITLE
Build SlackBot integration for TEC System upgrade status

### ISSUE THREAD

**Issue by ydan** [byuoitav/team#16]

**Comment by jessemillar** [comment]
Can this be moved to the [av-api](https://github.com/byuoitav/av-api) repo since the Slackbot will just be a front for the API?

**Comment by ydan** [comment]
It’s a tool that uses the API, but it’s not part of the API itself, right?

**Comment by jessemillar** [comment]
True. I'll make a repo specifically for it.
