### ISSUE TITLE
As the support manager, I want to know if the new SONY Z66 will work properly with the Pi system.

### ISSUE THREAD

**Issue by jpw547** [byuoitav/team#161]
(If the projector has been delivered...)
- [x] Test API commands in Postman
- [x] Write a microservice (or changes to a microservice) to interface with the projector
- [ ] Load test the microservice

**Comment by jpburnett** [comment]
I hooked up and tested the Sony Z66 projector using the pjlink microservice. All of the commands worked with the projector. Right now the projector is hooked up to ITB-1108B-D1. All that is left to do is load testing then we are finished!

**Comment by jpburnett** [comment]
The projector will be set up in some room this week to begin the load testing.
