### ISSUE TITLE
As the business team, we want a low cost projection solution to offer to customers.

### ISSUE THREAD

**Issue by jpw547** [byuoitav/team#165]
- [x] Finish Panasonic microservice
- [x] Projector load testing

**Comment by jpburnett** [comment]
The majority of the Panasonic projector microservice is done. All that is left to do on it is have the status functions return the correct XML feedback from the projector.

**Comment by jpburnett** [comment]
Panasonic Microservice is done!

**Comment by jpburnett** [comment]
Load Testing is done.
