### ISSUE TITLE
Front end for UI config

### ISSUE THREAD

**Issue by mandersonpjm** [byuoitav/team#188]
- [x] Merge newroom and editroom tabs
 - If no UIConfig is found, go to newroom. If a UIConfig is found for that room, go to editroom.
 - Change Finish() to account for new and updating
- [ ] Get the template filling working
 - It needs to fill without having to toggle any buttons
- [ ] Get some real templates made 
 - maybe look at some actual data to find what the most common ones are
- [x] Fix server webpage issues (refreshing, redirecting, CAS, etc.)
- [x] Add feedback in some form upon button clicks
- [x] Stop chaining slaves together, ya evil.
- [x] Fine tune styling for different window sizes

**Comment by mandersonpjm** [comment]
#173

**Comment by jpw547** [comment]
Styling is gonna be what it is gonna be until the final final final version is confirmed.

**Comment by jpw547** [comment]
The slave chain is just gonna be a thing that the user will have to avoid for now. If it becomes an issue then I will fix it, but right now there is not a good solution.

**Comment by jpw547** [comment]
It looks like CAS and CORS don't play well... In fact some googling around makes it seem like it may not work ever. We'll have to discuss this when Joe gets back in.

**Comment by xuther** [comment]
Need to implement Sessions
