### ISSUE TITLE
As the business team, we want a low cost projection solution to offer to customers.

### ISSUE THREAD

**Issue by mandersonpjm** [byuoitav/team#190]
- [x] Load Test the NEC
- [x] Longevity Test the NEC
- [x] Sony Longevity Test
- [x] Hold Demo Meeting

**Comment by mandersonpjm** [comment]
Need to have a show and tell meeting by the 16th of July.

**Comment by jpburnett** [comment]
Load testing the NEC went well, it hung up after making 20 concurrent calls every 0.5 seconds, but it would recover shortly thereafter.

**Comment by jpburnett** [comment]
Starting Longevity testing to run over the holiday through Thursday.

**Comment by jpburnett** [comment]
Had to fix some things, restarted the Longevity test to run it more. Prepped most of the microservice to get dockerized

**Comment by jpburnett** [comment]
All thats is left is to hold the meeting which will be done on Monday.

**Comment by jpburnett** [comment]
We are going to roll out stuff to see how the Sony projectors work and see if we want to keep that going. The NEC will be tested as well and we will see how we like things later.
