### ISSUE TITLE
Test NEC projector

### ISSUE THREAD

**Issue by mandersonpjm** [byuoitav/team#192]

**Comment by mandersonpjm** [comment]
#190

**Comment by jpburnett** [comment]
Just finished the Microservice. Waiting to hear back from Relia on whether or not Phillip will bring by the Demo unit again or if NEC will send us a demo unit

**Comment by jpburnett** [comment]
There is an issue with querying the volume status of the projector. I have been working with an Engineer from NEC to see what the options are. Most all other commands have been implemented.

**Comment by jpburnett** [comment]
There has been no response from Will (the NEC Engineer...) I will try to test one more time to see what I can figure out.

**Comment by jpburnett** [comment]
John and I tried literally all the 255 possibilities of finding a way to get it to work...The NEC could work, but only if the Engineers from NEC gave us access to the API they used to write their own projector communication tool.
