### ISSUE TITLE
As a support technician I want to have the state of other attributes (microphone batteries, etc) reported up.

### ISSUE THREAD

**Issue by AmmonMayfield** [byuoitav/team#216]
- [x] Validate the Shure microservice is generating events
- [x] Work on detail state pushing to ELK

**Comment by mandersonpjm** [comment]
Build from the Shure side.

**Comment by dannyrandall** [comment]
We should update the [shure microservice](https://github.com/byuoitav/shure-microservice) to use the new logging and error packages in [common](https://github.com/byuoitav/common)

**Comment by xuther** [comment]
This is working now. We need to make sure that all the rooms with wireless microphones have a receiver configured with the 'receiver' role. 

It's worth noting that eventually we'll need to get some configuration around this to support complex (shared receiver across rooms, multi receiver rooms. etc. etc.)
