### ISSUE TITLE
Solidify the automation of the touchpanel updates

### ISSUE THREAD

**Issue by ghost** [byuoitav/team#25]
- [x] Report Error/success to the Server
- [x] Remove .puf files before firmware update
- [x] Check Error success via firmware version and project timestamp
- [x] Pull .VTZ and Firmware from centralized location

**Comment by ydan** [comment]
From Joe 19 days ago:

> I'm at the point to try and ensure parsing of errors so we don't report a false success.
We're getting occasion where we're reporting a failure (timeout) while the touchpanel is updating.

**Comment by jessemillar** [comment]
The FTP microservice is capable of pulling remote files now.
