### ISSUE TITLE
As a developer I want to test the 32x32 video switcher and work.

### ISSUE THREAD

**Issue by jpburnett** [byuoitav/team#278]
- [x] Load Test the 8x8
- [x] Write new service to handle the 32x32
- [x] Load test the 32 x 32

**Comment by mandersonpjm** [comment]
Also test the 8x8 video switcher in preparation for the HBLL 2210/2212 install.

**Comment by jpburnett** [comment]
Getting the 8x8 set up to start testing that bad boy out

**Comment by jpburnett** [comment]
I load tested the 8x8, everything was functional. The Switcher didn't halt service, it continued on processing requests.

**Comment by jpburnett** [comment]
We need to adjust some code for the 32x32 switcher that will get the status a half-second after the switcher executes a command. Editing the passthrough-microservice.

**Comment by dannyrandall** [comment]
Finished editing the [passthrough-microservice](https://github.com/byuoitav/passthrough-microservice). We can now configure an endpoint to delay, and have a different request/response url.

**Comment by dannyrandall** [comment]
Changed our approach - I increased the delay in the RMC3's code, so that just needs to be recompiled and deployed to an RMC3 to be tested.

**Comment by jpburnett** [comment]
Danny wrote a script to put a delay to get the response and I load tested the 32x32. Everything held under load. We will continue to address concerns/see what we can edit in the crestron code to have a more permanent solution.
