### ISSUE TITLE
Push the mass-usp-compiler to the team repo

### ISSUE THREAD

**Issue by ydan** [byuoitav/team#29]
The mass-usp-compiler is a generic tool, be it in TEC Lite or TEC HD, so let's put it in the team repo.

**Comment by ydan** [comment]
Let's use a path like /Tools/SimplPlus/mass-usp-compiler so that it's clear what tool it's for

**Comment by jessemillar** [comment]
Do you want this in a separate repository? Or just in a new folder inside the repo the currently houses it (in addition to the TEC Lite repo)?

**Comment by ydan** [comment]
Same repo for now

**Comment by ydan** [comment]
This isn't what I meant. It's a universal tool, so let's post it to https://github.com/byuoitav/team/tools/simplplus/mass-usp-compiler instead of the hd repo.

**Comment by jessemillar** [comment]
OH

**Comment by jessemillar** [comment]
Done. Finally. Forgot about this issue. My bad.

https://github.com/byuoitav/team/tree/master/tools/simplplus/mass-usp-compiler
