### ISSUE TITLE
Add timer to firstboot.sh

### ISSUE THREAD

**Issue by mandersonpjm** [byuoitav/team#293]

**Comment by mandersonpjm** [comment]
#174

**Comment by dannyrandall** [comment]
I edited `firstboot.sh` to have a longer timer, and changed the service file just a bit. These two just need to be updated when a new image is created. (https://github.com/byuoitav/raspi-deployment-microservice/commit/07d17991d04537acb10340016c43d6576f1ff192)

**Comment by dannyrandall** [comment]
We'll call this one done, and include it on the next image.
