### ISSUE TITLE
Migrate instance of current ELK setup to OIT's docker hub

### ISSUE THREAD

**Issue by ghost** [byuoitav/team#3]

**Comment by danclegg** [comment]
I believe hub-tmp has been decommissioned. Mike Weight is the best contact for this.

**Comment by jessemillar** [comment]
Are we still wanting to do this now that things are in Amazon's ELK stack?

**Comment by ydan** [comment]
We need to evaluate it. Scott and I were just talking how we handle things like network outages with an all-cloud solution.

**Comment by jessemillar** [comment]
Meaning BYU network outages? We could certainly keep things on premises to circumvent that (or at least most of that), but better development practice would be to build in a cache/queue on the TEC/DMPS that could just hold off on pushing for a while in the event of an outage.
