### ISSUE TITLE
Push updated code for couch and ADCP/NEC stuff to stage. 

### ISSUE THREAD

**Issue by xuther** [byuoitav/team#308]
- [x] Includes common dependency. 
- [ ] Need to deploy.

**Comment by jpburnett** [comment]
Current code is in stage for both the NEC and ADCP code

**Comment by jpburnett** [comment]
All the code should have the common dependency now.

**Comment by jpburnett** [comment]
I believe I have pushed all the code to the pies that are necessary. 
- ITB-1006
- ITB-1106
- ITB-3308 (Although this one was a maybe from what I heard?) 
- BNSN-W002 (Looked like it was working?)
- BNSN-W003 (Need to follow up on to get working)
