### ISSUE TITLE
Fusion Stage and Prod

### ISSUE THREAD

**Issue by xuther** [byuoitav/team#34]

**Comment by jessemillar** [comment]
I feel like this is getting close? @sdanieru, do we just need to populate data?

**Comment by sdanieru** [comment]
stage and prod are setup. We currently have the 8 or so ITB TEC HD rooms on stg. When the event forwarding business is resolved (if that ever happens) we should bring Ken's team in to help manually populate rooms on the prod server.

**Comment by jessemillar** [comment]
@danclegg Is this still relevant?
