### ISSUE TITLE
Simplify the Config endpoint

### ISSUE THREAD

**Issue by mandersonpjm** [byuoitav/team#341]
The config endpoint is the /configuration endpoint that returns all information about the room(Devices, pis, room). We need to add a secondary endpoint between us and the University API to make sure that we don't give out all information.

**Comment by mandersonpjm** [comment]
#222

**Comment by thailandmatt** [comment]
https://byu.box.com/s/4im168q4yjul4z8lgk8hiwslv0amc7dd
