### ISSUE TITLE
Build Test UI for AWS stuff.

### ISSUE THREAD

**Issue by mandersonpjm** [byuoitav/team#346]
Make a UI to be able to test a room (either a test room or a fake room). Ensure that events are coming through and everything is working as intended. Nothing fancy needed. Pretty Ugly. 

- [x] Create a front end page
- [x] Write websocket connection stuff on the server side
- [x] Write websocket connection stuff on the client side
- [ ] Test when Joe is done with the Hub stuff

* I wrote the front end page in the dev branch of configuration-database-tool so just use that so we don't have to spin up a new env

**Comment by mandersonpjm** [comment]
#222

**Comment by jpw547** [comment]
I think all that is left here now is to authenticate correctly and stuff so that the API in AWS can be used properly. Then the device should be fully operational, and then we can blow up Aalderaan.
