### ISSUE TITLE
Move Static Indicies to the Rapidmaster stack.

### ISSUE THREAD

**Issue by xuther** [byuoitav/team#355]

**Comment by xuther** [comment]
Indexes have been created. Still reworking the visualizations/saved searches to have cross cluster searching enabled.

**Comment by xuther** [comment]
We're blocked right now as we don't have permissions to set up cross-cluster searching and Jared Lau is out of town until next week.

**Comment by jpburnett** [comment]
We set up the new indexes on the new stack with all the new templates. The templates were put in to team/notes in case we need them in the future.
After a0f1a3b all is well.
