### ISSUE TITLE
Script creation of Beanstalk Environments

### ISSUE THREAD

**Issue by xuther** [byuoitav/team#378]

**Comment by mandersonpjm** [comment]
#222

**Comment by jpburnett** [comment]
Notes from Joe: Make sure it maintains the possibility to have a dev, stg, and prd environments.

**Comment by jpburnett** [comment]
Private subnet, public load balancer.

**Comment by jpburnett** [comment]
The script has been made! There will probably need to be future adjustments made, but it makes the things we need it to for now.
