### ISSUE TITLE
Create a microservice for the SONY rest API

### ISSUE THREAD

**Issue by dannyrandall** [byuoitav/team#416]

**Comment by jpburnett** [comment]
For this we need to make a microservice for the Sony projectors based off of the documentation. Easy, right?

**Comment by jpburnett** [comment]
- [ ] Add on the new web calls to the existing Sony microservice
- [ ] Test the microservice on the projector in 1108
- [ ] Put the projector/firmware in a room?

**Comment by jpburnett** [comment]
The deed is done. The new code is in the webapi branch of the sony-control-microservice - https://github.com/byuoitav/sony-control-microservice/tree/webapi
