### ISSUE TITLE
Pi control for audio only

### ISSUE THREAD

**Issue by mandersonpjm** [byuoitav/team#417]

**Comment by dannyrandall** [comment]
Completed in https://github.com/byuoitav/touchpanel-ui-microservice/commit/b4bcac2ff231246568162994c44f19fc4a5f9a76. The audio-only UI will happen when there are no `displays` specified in the preset. Also, by adding the feature `no-audio-groups` to the panel, all of the independent audio devices will show up in one tab, as opposed to being grouped by device type. 

This closes parent task https://github.com/byuoitav/team/issues/398.
