### ISSUE TITLE
Create a new mirror display role

### ISSUE THREAD

**Issue by mandersonpjm** [byuoitav/team#419]
- [x] Add "MirrorMaster" and "MirrorSlave" roles to the database
- [x] Add the mirror stuff to the command evaluators
- [x] Test with headless devices, like video cards

**Comment by mandersonpjm** [comment]
#197

**Comment by jpw547** [comment]
I added the "MirrorMaster" and "MirrorSlave" roles to the database. I also changed the command evaluators to account for this and tested it using D2 and D3 in 1101. All changes went smoothly, so I have pushed the code up and am opening a pull request to merge the changes into testing. I will then test in 1108.

**Comment by jpw547** [comment]
I will also start to add the necessary changes to the Database Tool to account for this. Essentially what needs to change is there needs to be some form of telling the devices that the mirroring will happen. Either by adding the roles to both devices or by creating a separate toggle button. 

This will also then need to reflect in the UI config section and let the user know that if there is a mirror slave display then they can have be API controlled, it will just get overridden if the master ever changes.

**Comment by jpw547** [comment]
1108 is a mess, so I ended up having to change 1108B. But now 1108B-CP1 shows only D1 on the Cherry setup, but it controls both D1 and D2. Feel free to test.

**Comment by jpw547** [comment]
Donezo

**Comment by dannyrandall** [comment]
I'm gonna reopen this as a reminder to fix the commands issue for devices that are being mirrored. https://github.com/byuoitav/av-api/blob/d353f6c142096457aae2b899f6178ec54a7131ee/statusevaluators/statusevaluators.go#L95 fails, and then any devices after that never get their status actions to the list, and are subsequently never evaluated for their status, and never return as part of the room.

**Comment by jpw547** [comment]
Status evaluation is good, I am re-closing this issue.
