### ISSUE TITLE
Make the `hostname` field in the Elastic `config` index not analyzed

### ISSUE THREAD

**Issue by jessemillar** [byuoitav/team#44]

**Comment by danclegg** [comment]
Done. Current index mapping is:

{
	"config_v4": {
		"mappings": {
			"cp": {
				"properties": {
					"ICN": {
						"type": "string",
            "index": "not_analyzed"
					},
					"description": {
						"type": "string",
            "index": "not_analyzed"
					},
					"dns": {
						"properties": {
							"ipAddress": {
								"type": "ip"
							}
						}
					},
					"gateway": {
						"type": "ip"
					},
					"hostname": {
						"type": "string",
            "index": "not_analyzed"
					},
					"ipAddress": {
						"type": "ip"
					},
					"macaddress": {
						"type": "string",
            "index": "not_analyzed"
					},
					"room": {
						"properties": {
							"building": {
								"type": "string",
  							"index": "not_analyzed"
							},
							"coordinates": {
								"type": "geo_point"
							},
							"floor": {
								"type": "string",
  							"index": "not_analyzed"
							},
							"nameOrNumber": {
								"type": "string",
  							"index": "not_analyzed"
							}
						}
					},
					"serial": {
						"type": "string",
            "index": "not_analyzed"
					},
					"subnetmask": {
						"type": "ip"
					}
				}
			}
		}
	}
}

**Comment by jessemillar** [comment]
Added to the [team wiki](https://github.com/byuoitav/team/wiki/Config-Index).
