### ISSUE TITLE
Make a list of demo hardware needed for Pi recognition

### ISSUE THREAD

**Issue by mandersonpjm** [byuoitav/team#475]

**Comment by xuther** [comment]
- [ ] NFC
- [ ] Thumbprint
- [ ] Camera (ribbon) 
- [ ] Bluetooth
- [ ] Mic 


- [ ] Aruba AP association
- [ ] Scheduling
- [ ] PIN
- [ ] Voice Recognition
- [ ] Files - ?Via?

**Comment by thailandmatt** [comment]
https://byu.box.com/s/l40rokahse1x5jv5fsxdanhxo6afdpkh
