### ISSUE TITLE
Start investigating install validation tool.

### ISSUE THREAD

**Issue by mandersonpjm** [byuoitav/team#493]

**Comment by xuther** [comment]
REfresh pi
Reboot pi
hard reboot

log into projector to see if its broken
do something simiar with the tv
power cycle tv
disable and re-enable network port
firmware checks
recycle / reboot via

signal path checks

mic batteries
EDID
microphones 
any sort of heat checks
sd flash card life
control matrix
screenshot 
pi control
override room sensor stuff??
supress alerts for a certain amount of time - with a reason why



advanced stuff for us
docker logs
mstatus type stuff
recent events
send events into mesh to test
versions
