### ISSUE TITLE
Tag docker images with version (other than "latest")

### ISSUE THREAD

**Issue by danclegg** [byuoitav/team#50]

**Comment by jessemillar** [comment]
We can certainly give versions in the name of organization, but isn't Amazon always going to be pulling `latest` anyway?

**Comment by ydan** [comment]
Yes, but in the spirit of versioning, we can try to do this too. I think we’re not encouraged to use “latest” when tagging, it’s a derived tag, right?

**Comment by jessemillar** [comment]
It is a derived tag. I'm not putting "latest" in manually anywhere, Docker is just putting that in on its own. I'll look into this tomorrow when I'm in. At the very least, knowing how to have Circle auto-tag images would be good knowledge to have.
