### ISSUE TITLE
Document the AWS Beanstalk setup process

### ISSUE THREAD

**Issue by jessemillar** [byuoitav/team#51]
Be sure to remember the issue of compressing files instead of directories when making the .zip to upload for the "First Version".

**Comment by danclegg** [comment]
Valid. I definitely zipped the directory.

**Comment by jessemillar** [comment]
Did you document the Beanstalk setup process somewhere or just close this for #reasons? 😛

**Comment by danclegg** [comment]
Reasons. Closing issue. (jk)

**Comment by jessemillar** [comment]
This is why I enjoy working in this team. 👍
