### ISSUE TITLE
Mitch buy a wallplate version of JAP

### ISSUE THREAD

**Issue by thailandmatt** [byuoitav/team#535]

**Comment by thailandmatt** [comment]
VBS-HDIP-717WP2
should be $1090.44

That's like double the cost of just a transmitter, so I may want to talk with Mike / Evan and see if we can't come up with a way to just stick the transmitter itself in the wall - that would sure be cheaper.

Anyway, if you could get one for us that'd be great so we can test anyway.

**Comment by mandersonpjm** [comment]
Demo unit is being shipped. The tracking number is 1ZY566V00397491761.
