### ISSUE TITLE
Research ADDER View

### ISSUE THREAD

**Issue by mandersonpjm** [byuoitav/team#554]

**Comment by steverett8132** [comment]
hoping to get a call monday from the sales rep to determine if this will work for us,  the biggest hold back i see right now is that it is limited to 2 monitors and i have been told they currently use 4 monitors

**Comment by steverett8132** [comment]
Demo should be here on Friday

**Comment by steverett8132** [comment]
Played with it a little but it appears that the cost is above our budget so we are looking a different way.
