### ISSUE TITLE
Set up a couple of pis from scratch, and create a document that we can give to LDSBC and have them set up a their last couple Pis

### ISSUE THREAD

**Issue by dannyrandall** [byuoitav/team#589]
The pis need
- [x] i3
- [x] xorg
- [x] docker
- [x] chromium
- [x] Add the change room script
- [x] Auto run chromium from i3 (edit ~/.i3/config)
- [x] NTP setup
- [x] Auto log in
- [ ] Come up with patch cycle instructions

**Comment by thailandmatt** [comment]
.i3config
screen shutoff binary
.xinitrc
