### ISSUE TITLE
Add endpoints to gather hardware information about the client devices.

### ISSUE THREAD

**Issue by dannyrandall** [byuoitav/team#595]
_*Devices*_
- [x] Sony PHZ10
- [x] Sony FHZ66/65
- [x] NEC Projectors
- [x] Sony Bravia TVs
- [x] Kramer switchers
- [x] Just + Power switchers
- [x] Pulse Eight switchers
- [x] QSC
- [x] Blu
- [x] Vias

_*Information*_
- MAC address
- Serial Numbers 
- Firmware Version
- IP Address?
- Build Date? 
- Lens/other information
- Run hours? 
- Etc. Etc.

**Comment by jpw547** [comment]
It is done
