### ISSUE TITLE
Enable HTTPS on AWS microservices

### ISSUE THREAD

**Issue by jessemillar** [byuoitav/team#60]

**Comment by jessemillar** [comment]
Waiting on Networking. We've configured everything we can.

**Comment by sdanieru** [comment]
networking has now pointed avs.byu.edu to AWS Route 53. I've added the A records for the 9 applications we currently have up; just waiting to get a digicert account so I can create a cert to front avs.byu.edu then we should be set: clients using https which terminates at the load balancers for our applications.
