### ISSUE TITLE
Document AWS to BYU network configuration

### ISSUE THREAD

**Issue by jessemillar** [byuoitav/team#61]
Throw in some security analysis for kicks and giggles.

**Comment by sdanieru** [comment]
on my TODO list is automating our environment setup/teardown with AWS cloudformation; then we can document env with code in the repo

**Comment by jessemillar** [comment]
Was any progress ever made with CloudFormation? Is documentation good for when you leave, @sdanieru?

**Comment by sdanieru** [comment]
Unfortunately no, but I'll make sure I put together a wiki page for our current AWS environment before I take off.

**Comment by jessemillar** [comment]
Networking should have this information if we ever need it.
