### ISSUE TITLE
Make a script that scans for dead links on wiki pages

### ISSUE THREAD

**Issue by jessemillar** [byuoitav/team#68]

**Comment by danclegg** [comment]
@jessemillar What is your intended framework for this?

**Comment by jessemillar** [comment]
I never really found one. It's a bit trickier than I thought it'd be.

It can be accomplished in a ghetto manner with [this Python package](https://wummel.github.io/linkchecker/). Rate limits are definitely a thing though because it's a bot and the only way I got it to work was by spoofing that I was actually the Google crawler.

```
linkchecker --user-agent="Googlebot" -r=0 https://github.com/byuoitav/team/wiki
```
