### ISSUE TITLE
Video conferencing productization list resolution.

### ISSUE THREAD

**Issue by mandersonpjm** [byuoitav/team#685]

**Comment by mandersonpjm** [comment]
Problems
-Auto on/off
-Need camera/mic select defaulted

**Comment by steverett8132** [comment]
I have reached out to Jill and Matt Kiefer to see what is possible in setting the default for the machine,  it is possible for each user but looking into doing per machine.

**Comment by steverett8132** [comment]
Still waiting to hear back from duders upstairs.
