### ISSUE TITLE
Complete microservice documentation

### ISSUE THREAD

**Issue by danclegg** [byuoitav/team#70]
On the [microservice documentation page](https://github.com/byuoitav/team/wiki/Making-a-Microservice) are the following links that have no content:

- [ ] https://github.com/byuoitav/team/wiki/Circle-CI#starting-a-build-on-circle
- [ ] https://github.com/byuoitav/team/wiki/Circle-CI#environment-variables
- [ ] https://github.com/byuoitav/team/wiki/Circle-CI#slack-integration
- [ ] https://github.com/byuoitav/team/wiki/Circle-CI#aws-integration

**Comment by jessemillar** [comment]
Fixed. It was just a linking error.
