### ISSUE TITLE
Inter-container communication on AWS is broken

### ISSUE THREAD

**Issue by xuther** [byuoitav/team#73]
We need to disable WSO2 authentication and enable HTTPS for all our services when they're communicating amongst themselves.

**Comment by jessemillar** [comment]
As of now, the best solution is to probably hang on to the JWT token and pass it on to the microservice that is being communicated with. There may be optimizations we can make so that we don't have to make a million verification calls to WSO2. #latency

**Comment by jessemillar** [comment]
We're currently fiddling with the idea of passing around a generated API key that will circumvent the JWT checking without talking to WSO2.
