### ISSUE TITLE
Validate Wireless Scheduling Panel Infrastructure in ITB

### ISSUE THREAD

**Issue by mandersonpjm** [byuoitav/team#819]

**Comment by jpburnett** [comment]
In terms of powering the displays, David has said that PoE is the way to go. I have looked in to ways to power a pi through PoE, and we have a couple of options:

**Comment by jpburnett** [comment]
Daniel Wells let us know that the plan is to use managed switches to power the Pis over PoE using the Cisco switches. Pis have worked with that and we will know how to use it it the future.
