### ISSUE TITLE
Investigate windowing processor API for WSC Video wall

### ISSUE THREAD

**Issue by mandersonpjm** [byuoitav/team#832]

**Comment by jpburnett** [comment]
So far I've taken a look at the skreens API and the tvone api. The tvone api looks more trivial to implement seeing as they have most everything documented, the skreens api can still be used.

**Comment by jpburnett** [comment]
I made a write up of my investigations in to the API for tvONE and skreens. I uploaded it to Matt's folder in box labeled as "Video Wall API Documentation". Suggestions and time estimates were put in the document as to what further steps could be in a decision. 

I played around with the skreens device we have, it is still set up in 1108 if others would like to play around with it as well.
