### ISSUE TITLE
Create a microservice for overflow streams

### ISSUE THREAD

**Issue by thailandmatt** [byuoitav/team#842]
- [x] Build a "switching stream" page
- [ ] Have the microservice serve up the webpages
- [ ] Test switching speed via the shell script, make sure we are getting comparable times
- [ ] Test all types of streams

**Comment by thailandmatt** [comment]
help: http://www.settopbox.sk/amino/Configuration_Guide.pdf

**Comment by mandersonpjm** [comment]
Moving this to a future sprint. Awaiting a conversation between Brandon and the AV Events team.

**Comment by thailandmatt** [comment]
Decision made - make the pi do it
- link from wells: https://github.com/jleight/omxplayer
