### ISSUE TITLE
Update "IPTV" source in CONF rooms to say "Overflow"

### ISSUE THREAD

**Issue by mandersonpjm** [byuoitav/team#846]

**Comment by thailandmatt** [comment]
@mandersonpjm which icon do you want for the UI on these?
![image](https://user-images.githubusercontent.com/31248374/57730047-da1a5500-7654-11e9-894e-ef604c448b16.png)

**Comment by mandersonpjm** [comment]
@thailandmatt Which icon did it have before? The same as the HDMI one?
