### ISSUE TITLE
Test the catchbox kits

### ISSUE THREAD

**Issue by mandersonpjm** [byuoitav/team#879]

**Comment by mandersonpjm** [comment]
There are no XLR's in the LSB where they want this installed.

**Comment by thailandmatt** [comment]
Waiting for new unit to come back from Catchbox

**Comment by thailandmatt** [comment]
Per Anthony:
"3 out of 5"
"The catch box works decent. It is nice that the new receiver has an XLR output. The unit as a whole is noisy; a hiss can be heard. It's more noticeable in some rooms than others depending on the gain structure of the system. We are going to test in a few more spaces."
"If you plan on using the quarter-inch line out on the receiver, you need to have an unbalanced input,"
