### ISSUE TITLE
Figure out HDMI matrix device

### ISSUE THREAD

**Issue by xuther** [byuoitav/team#92]
- Probably a new microservice
- Need to find IP controllable HDMI matrix (probs 8x8 for that room)

**Comment by jessemillar** [comment]
I vote for that one that Daniel Wells was mentioning from the company based in the UK.

**Comment by jessemillar** [comment]
Related: https://github.com/byuoitav/av-api/issues/92

**Comment by jessemillar** [comment]
https://github.com/byuoitav/pulse-eight-neo-microservice
