### ISSUE TITLE
Talk to the Weigand NFC readers

### ISSUE THREAD

**Issue by mandersonpjm** [byuoitav/team#977]
Write a microservice similar to the "room auth" microservice that uses the new NFC readers
- [x] Discard anything that isn't 48 bits
- [x] If we get a valid 48 bits, then parse the SEOS number, call the persons API
- [x] Send the event

**Comment by thailandmatt** [comment]
- [ ] Discard anything that isn't 48 bits
- [ ] If we get a valid 48 bits, then parse the SEOS number, call the persons API and send the event
