### ISSUE TITLE
One little cherry bug to fix

### ISSUE THREAD

**Issue by thailandmatt** [byuoitav/team#982]
![image](https://user-images.githubusercontent.com/31248374/60607777-33f8ea80-9d7b-11e9-98de-e54f74860d75.png)

**Comment by dannyrandall** [comment]
`15vw` -> `19vw` in `.device` and `.volume` seems to do the trick, but we can only fit four sliders (down from five) on each page if we do that.

**Comment by thailandmatt** [comment]
check vertical (make sure it doesn't get hidden by the text)
push it to stage - push to ITB - add to magic john release notes doc

**Comment by jpw547** [comment]
Fixed. Merging into stage and then I will deploy to the ITB
